name: Documentation

on:
  push:
    branches:
      - dev-docsHosting
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup environment
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia_version }}

      - uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: |
            ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('Artifacts.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
      - uses: actions/cache@v2
        env:
          cache-name: cache-packages
        with:
          path: |
            ~/.julia/packages
            ~/.julia/compiled
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('test/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
      - name: Install documentation dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.build(verbose=true); Pkg.instantiate()'

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        run: |
          xvfb-run julia --color=yes --project=docs/ -e 'include("docs/make.jl")' 
