name: Documentation

on:
  push:
    branches:
      - dev-docsHosting
    tags: '*'
  pull_request:

jobs:
  docs:
    name: 'Documentation: ${{ matrix.makejl }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jlenv: 'docs/'
            makejl: 'docs/make.jl'
          - jlenv: 'docs/pdf/'
            makejl: 'docs/pdf/make.jl'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=${{ matrix.jlenv }} -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=${{ matrix.jlenv }} --color=yes ${{ matrix.makejl }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
